### ISSUE TITLE
Add Bearer Authentication support

### ISSUE THREAD

**Issue by thejhh** [pvarki/python-pvas-pttbackend#2]
The PTT backend currently is a microservice that handles user authentication using cookies. However, we need to update it to use Bearer Authentication instead. This will improve security and provide better support for modern web applications.

To achieve this, we need to do the following:

* [ ]  Update the microservice to support Bearer Authentication.

Once these changes are made, the microservice will support Bearer Authentication and any frontend applications that use it will be able to authenticate using a Bearer token.

The Bearer auth support is added in https://github.com/pvarki/python-pvas-arkia11napi/issues/4

**Comment by rambo** [comment]
It already supports bearer see https://github.com/pvarki/python-pvas-arkia11napi/blob/main/src/arkia11napi/security.py#L107, reopen as bug in python-pvas-arkia11napi if this is not the case after testing.
